### PR TITLE
Add LLVM 14

### LINKED ISSUE #20: Add clang 14
* Clang 14 has been out since March, would be nice to have a Docker image for it as well.

### PR DESCRIPTION
**Pull request by Skylion007**
* This adds clang-14
* Closes #20

### CODE REVIEW

**Comment by Skylion007** [comment]
@silkeh I've gone and updated all the older Docker images lying around as well.

**Comment by silkeh** [comment]
Thanks a lot for this! Unfortunately, it seems that some of the builds failed. Causes are as follows:

- 8.0.1 and 9.0.1 were not released for Ubuntu on AMD64 on the original releases page.
- 10.0.1 was not released for Ubuntu 18.04.
- 11.0.1 was only released for Ubuntu 18.04 and 20.10, not 20.04.
- 12.0.1 was only released for Ubuntu 16.04, not 20.04.
- 13.0.1 was only released for Ubuntu 18.04, not 20.04.
- 14.0.0 was only released for Ubuntu 18.04, not 20.04.

**Comment by Skylion007** [comment]
@silkeh I reverted those updates.

**Comment by Skylion007** [comment]
I'll split those updates into a separate PR. For now, I just want to have clang 14 support merged.

**Comment by Skylion007** [comment]
@silkeh Hopefully final time, 14.0.0 is the latest release relevant to Ubuntu.

**Comment by silkeh** [comment]
LGTM, thanks!

**Comment by henryiii** [comment]
Is it okay to update these to the latest patch releases? There's a bad clang-tidy bug fix needed for pybind11 in 14.0.5. I can do it if so.

**Comment by Skylion007** [comment]
@henryiii We have to wait for the binaries for Ubuntu to be uploaded to the Github release. I expect that to be done by tomorrow or Monday based on past upload https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.5

**Pull request merged**
